
server:
  port: 8080

#documentation
springdoc:
  use-management-port: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# profile and actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 9090

# Logging
logging:
  file:
    path: C:\PURAB\GITHUB-PROJECTS\SPRING-BOOT-PROJECTS\spring-boot-redis-user-mangement-example-ep\logs
    name: logs\user.log
  logback:
    rollingpolicy:
      max-file-size: 10KB
  level:
    root: info
    ep-dao: debug
    ep-controller: info
    ep: info
  group:
    spring: "org.springdoc, org.springframework"
    ep: "in.purabtech.ep"

#debug: true

#Cache config
spring:
  cache:
    redis:
      time-to-live: 1025
    type: simple

  redis:
    port: 6379
